package org.androidtown.sleeper.propclasses.com_manager;

import android.util.Log;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clResponseMessage
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook
//  @ Email : rkdtlsdnr102@naver.com


/**
 * Make, dissolve response message to/from remote device. Currently, there is no use of making
 * response message since response message is always made and sent from ap by the request message
 * sent from app side. But for future modification, we remain code for making.
 */
public class clResponseMessage extends clMessage {

    private byte ResponseType ;
    public static final byte SUCCESS=0x02 ;
    public static final byte FAIL=0x03 ;

    public clResponseMessage(){

        super() ;
        Header= clMessage.RES ;
    }

    public clResponseMessage(byte _devID, String _devMsg){

        super(_devID,_devMsg) ;
        Header= clMessage.RES ;
    }

    /**
     * set response type of response message after processing request.
     * @param _resType SUCCESS for request processed successfully, FAIL for otherwise.
     */
    public void setResponseType(byte _resType){

        ResponseType=_resType ;
    }

    /**
     * Get response type
     * @return SUCCESS for request processed successfully, FAIL for otherwise.
     */
    public byte getResponseType(){

        return ResponseType ;
    }

    @Deprecated
    @Override
    public String makeMessage(){

        String resMsg=(char)RES+"\n"+(char)ResponseType+"\n"+(char)DeviceID+
                "\n"+devMsg+"\n" ;

        return resMsg ;
    }

    @Override
    public void dissolveMessage(String message){

        setResponseType((byte)(message.charAt(2))) ;
        setDeviceID((byte)(message.charAt(4))) ;
        setDeviceMessage(message.substring(6,message.length() - 1)) ;

        String ctrlInfo=devMsg ;

        for(int i=0;i<ctrlInfo.length();i++)
        {
            Log.i("resmsg DeviceMsg:", Integer.toHexString(ctrlInfo.charAt(i))+" ") ;
        }
    }
}
