package org.androidtown.sleeper.endclasses;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clMyDatabase.java
//  @ Date : 2015-08-13
//  @ Author : Kang Shin Wook, Kim Hyun Woong
//
//


import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.DatabaseErrorHandler;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import org.sleeper.propclasses.dataprocessor_manager.clDataProcessor;

import java.util.ArrayList;
import java.util.List;


/**
 * User defined database manage class. It should not directly manipulate SQLiteDatabase object. All
 * user's database manage class should implement clDataProcessor.clDatabaseManager.IDbChangeListener
 * and get SQLiteDatabase object by overriding setDB method. And user defined database manager should
 * only manipulate update, insert, delete when
 */
public class clDatabaseManager extends SQLiteOpenHelper{

	//define MBD Table : Measure-By-Date Table
	private static final String dbName="SleeperDB";
	public static final String MBDTable ="MBDTable" ;
	public static final String colId="_id" ;
    public static final String colDate="Date" ;
	public static final String colSleepTime="SleepTime" ;
	public static final String colWakeTime="WakeTime" ;
	//define MBT Table : Measure-By-Time Table
	public static final String MBTTable ="MBTTable" ;
    public static final String colTime ="Hour";
	public static final String colTemp ="Temperature";
    public static final String colSleepState ="SleepState";
	public static final String colDecisionValue="DecisionValue" ;


	public clDatabaseManager(Context context) {
		super(context, dbName, null, 1);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {

        db.execSQL("CREATE TABLE " + MBDTable + " (" +colId+" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "+colDate+" TEXT, "+colSleepTime + " INTEGER NOT NULL, "
                + colWakeTime + " INTEGER, "
                + "UNIQUE("+colSleepTime+","+colId+")"
                +")");

        //create datatable_summary
        db.execSQL("CREATE TABLE " + MBTTable +"("+colSleepTime+" INTEGER, "+ colTime+" INTEGER, " + colTemp+ " INTEGER, "
                + colSleepState+" INTEGER, "+colDecisionValue+" INTEGER, "
                +"PRIMARY KEY("+colSleepTime+","+colTime+"), "
                +"FOREIGN KEY("+colSleepTime+") REFERENCES "+MBDTable+"("+colSleepTime+") ON DELETE CASCADE"
                +")");
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

	}
}
