package org.androidtown.sleeper.propclasses.com_manager;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clRequestMessage
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook
//  @ Email : rkdtlsdnr102@naver.com


/**
 * Make, dissolve request message to/from remote device. Currently, there is no use of dissolving
 * request message since request message is always made and sent from app side and ap device only
 * work as server. But for future modification, we remain code for dissolving.
 */
public class clRequestMessage extends clMessage {


    /**
     * Constructor
     */
    public clRequestMessage(){

        super() ;

        Header= clMessage.REQ ;
    }


    @Deprecated
    public clRequestMessage(byte _devID, String _devMsg){

        super(_devID,_devMsg) ;
        Header= clMessage.REQ ;
    }

    @Override
    /**
     * Make request message
     */
    public String makeMessage(){

        String reqMsg= (char)REQ+"\n"+(char)DeviceID+"\n"+devMsg+"\n" ;

        return reqMsg ;
    }

    @Deprecated
    @Override
    public void dissolveMessage(String message){

        setDeviceID((byte)(message.charAt(2))) ;
        setDeviceMessage(message.substring(5, message.length() - 2)) ;

    }
}
