//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clStatManagerAlpha
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook, Kim Hyun Woong, Kim Hyun Woo
//  @ Email : rkdtlsdnr102@naver.com

package org.androidtown.sleeper.propclasses.dataprocessor_manager;

import com.jjoe64.graphview.series.DataPoint;

import java.util.ArrayList;
import java.util.List;

@Deprecated
public class clStatManagerAlpha {
	private String HorizontalAxisName;
	private String VerticalAxisName;
	private List<DataPoint[]> FirstScaleDataList;
	private List<String> FirstScaleDataNameList;
	private List<DataPoint[]> SecondScaleDataList ;
	private List<String> SecondScaleDataNameList ;
	private String HorizontalAxisFormatString ;
	private int toCalcAvgSeriesIndex=0 ;
	private int toCalcAvgSeriesScale=FIRST ;
	public static final int FIRST=0x00 ;
	public static final int SECOND=0x01 ;

	public clStatManagerAlpha() {

		FirstScaleDataList =new ArrayList<>() ;
		FirstScaleDataNameList =new ArrayList<>() ;
		SecondScaleDataList=new ArrayList<>() ;
		SecondScaleDataNameList=new ArrayList<>() ;
	}

	//set horizontal axis name
	public void setHorizontalAxisName(String name) {

		HorizontalAxisName=name ;
	
	}

	//set vertical axis name
	public void setVerticalAxisName(String name) {

		VerticalAxisName=name ;
	}

	public void setHorizontalAxisFormatString(String _formatString){

		HorizontalAxisFormatString=_formatString ;
	}

	public void setToCalcAvgData(int scaleType,int index){

		toCalcAvgSeriesScale=scaleType ;
		toCalcAvgSeriesIndex=index ;
	}


	//add data array with name
	public void addData(int scaleType,String DataName, DataPoint[] data){

		if(scaleType==FIRST) {
			FirstScaleDataList.add(data);
			FirstScaleDataNameList.add(DataName);
		}
		else
		{
			SecondScaleDataList.add(data) ;
			SecondScaleDataNameList.add(DataName) ;
		}
	}

	//get data array by index in order when it was added in the data list
	public DataPoint[] getData(int scaleType,int index){

		if(scaleType==FIRST)
			return FirstScaleDataList.get(index) ;
		else
			return SecondScaleDataList.get(index) ;
	}

	//get name of array by index in order when it was added in the data name list
	public String getDataName(int scaleType,int index){

		if(scaleType==FIRST)
			return FirstScaleDataNameList.get(index) ;
		else
			return SecondScaleDataNameList.get(index) ;
	}

	/**
	 * calculate average from series that was designated as toCalcAvgSeries
	 * @return average of toCalcAvgSeries' values
	 */
	public double getAvg(){

		DataPoint[] avgDataPointArray=null ;

		if(toCalcAvgSeriesScale==FIRST)
			avgDataPointArray= FirstScaleDataList.get(toCalcAvgSeriesIndex) ;
		else
			avgDataPointArray= SecondScaleDataList.get(toCalcAvgSeriesIndex) ;

		long total=0 ;

		for(DataPoint dPoint : avgDataPointArray){

			total+=dPoint.getY() ;
		}

		return ((double)total/avgDataPointArray.length) ;
	}

	public String getHorizontalAxisFormatString(){

		return HorizontalAxisFormatString ;
	}

	//get horizontal axis name
	public String getHorizontalAxisName() {

		return HorizontalAxisName ;
	}

	public int getDataSize(){

		return FirstScaleDataList.size() ;
	}

	//get vertical axis name
	public String getVerticalAxisName() {

		return VerticalAxisName ;
	}
}
