//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clDataProcessor.java
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook, Kim Hyun Woong
//  @ Email : rkdtlsdnr102@naver.com
//
//
// Copyright (C) 2015  Kang Shin Wook, Kim Hyun Woong
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

package org.androidtown.sleeper.sleep_manage_activity;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.wifi.WifiManager;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import org.androidtown.sleeper.R;

public class SleepManageFragment extends Fragment{

    private AutoModeFragment automodeFragment=null ;

    View rootView=null ;
    private WifiReceiver wifiReceiver=null ;
    private String connectedDeviceName="" ;


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState){

        //inflate layout_sleep_manage layout into its fragment
        rootView= inflater.inflate(R.layout.layout_sleep_manage,container,false) ;

        //Log.i(toString(), "On Create View called") ;

        //manually create auto mode fragment
        automodeFragment=new AutoModeFragment() ;

        getChildFragmentManager().beginTransaction().replace(R.id.flayoutMode,
                automodeFragment,AutoModeFragment.Tag).commit() ;

        return rootView ;
    }


    @Override
    public void onResume() {

        //create wifireceiver to receive wifi state change broadcast
        IntentFilter filter=new IntentFilter() ;
        filter.addAction(WifiManager.NETWORK_STATE_CHANGED_ACTION) ;
        wifiReceiver=new WifiReceiver() ;
        getActivity().registerReceiver(wifiReceiver, filter) ;
        //Log.i(toString(), "OnCreate called") ;
        super.onResume();
    }


    //it will be called when this fragment destroyed on view, especially when replaced by other
    @Override
    public void onPause() {

        getActivity().unregisterReceiver(wifiReceiver);
        super.onPause();
    }

    /**
     * Wifi state change receiver
     */
    private class WifiReceiver  extends BroadcastReceiver {

        @Override
        public void onReceive(Context context, Intent intent) {


            if (intent.getAction().equals(WifiManager.NETWORK_STATE_CHANGED_ACTION)) {


                if (isConnectedViaWifi(context)) {
                    TextView textViewConnectedDevice = (TextView) rootView.findViewById(R.id.textViewConnectedDevice);

                    WifiManager wifiManager = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);


                    connectedDeviceName = wifiManager.getConnectionInfo().getSSID();

                    connectedDeviceName=connectedDeviceName.substring(1,connectedDeviceName.length()-1) ;
                    textViewConnectedDevice.setText(getResources().getString(R.string.connected_device) + connectedDeviceName);


                } else {
                    TextView textViewConnectedDevice = (TextView) rootView.findViewById(R.id.textViewConnectedDevice);
                    connectedDeviceName="" ;
                    textViewConnectedDevice.setText(getResources().getString(R.string.no_connected_device));
                }
            }
        }

        /**
         * checks if app is currently connected via wifi
         * @return true if connected, otherwise false
         */
        private boolean isConnectedViaWifi(Context context) {
            ConnectivityManager connectivityManager = (ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);
            NetworkInfo mWifi = connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI);


            return mWifi.getState().equals(NetworkInfo.State.CONNECTED) ;
        }
    }
}
