//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clDataProcessor.java
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook, Kim Hyun Woong
//  @ Email : rkdtlsdnr102@naver.com
//
//
// Copyright (C) 2015  Kang Shin Wook, Kim Hyun Woong
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

package org.androidtown.sleeper;

import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.os.Bundle;
import android.widget.Toast;

import org.androidtown.sleeper.endclasses.clAccelTempDataProcessor;
import org.androidtown.sleeper.sleep_manage_activity.DuringSleepFragment;
import org.sleeper.propclasses.app_manager.clApp;
import org.sleeper.propclasses.dataprocessor_manager.clDataProcessor;

/**
 * Main activity. It is nothing more than just central repository for many fragment. It currently
 * only offers access app and fragment manager.
 */
public class MainActivity extends FragmentActivity {

    /**
     * App model that controls basic app performance(e.g wifi, alarm service)
     */
    private clApp App =null ;//
    private clAccelTempDataProcessor acTempProcessor=null ;

    /**
     * View pager fragment which is main fragment
     */
    private Fragment viewPagerFragment=null ;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //create user defined dataprocessor and attach to app
        App = new clApp(this,clDataProcessor.getInstance(this)) ;
        acTempProcessor=new clAccelTempDataProcessor(this) ;
        clDataProcessor.getInstance(this).registerListener(acTempProcessor);

        //create view pager fragment and inflate in fragmentContainer
        //in fragmentContainer frame layout, different views are attached, including
        //table's view and also other views that need to cover all screen.
        viewPagerFragment=new ViewPagerFragment() ;
        getSupportFragmentManager().beginTransaction().replace(R.id.fragmentContainer, viewPagerFragment, ViewPagerFragment.Tag).commit();

    }

    public clAccelTempDataProcessor getProcessor(){

        return acTempProcessor ;
    }

    /*
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
    */

    @Override
    protected void onResume() {

        App.onResume() ;
        super.onResume();
    }

    @Override
    protected void onPause() {

        App.onPause() ;
        super.onPause();
    }

    @Override
    protected void onDestroy() {

        App.onDestroy();
        super.onDestroy();
    }

    /**
     *Returns App model
     * @return App model
     */
    public clApp getApp(){

        return App;
    }

    @Override
    public void onBackPressed() {

        if(getSupportFragmentManager().findFragmentByTag(DuringSleepFragment.Tag)!=null) {
            App.stopSleepMode();
            Toast.makeText(this, "Sleep Mode Stopped", Toast.LENGTH_SHORT).show();
        }

        super.onBackPressed();
    }

}
