//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Sleeper
//  @ File Name : clDataProcessor.java
//  @ Date : 2015-09-06
//  @ Author : Kang Shin Wook, Kim Hyun Woong
//  @ Email : rkdtlsdnr102@naver.com
//
//
// Copyright (C) 2015  Kang Shin Wook, Kim Hyun Woong
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 2 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along
//  with this program; if not, write to the Free Software Foundation, Inc.,
//  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

package org.androidtown.sleeper;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import org.androidtown.sleeper.sleep_manage_activity.SleepManageFragment;
import org.androidtown.sleeper.statistic_manage_activity.StatisticManageSelectFragment;

/**
 * ViewPagerFragment. This manages table view. Currently, there're only Sleep, Statistic tables
 * attached to this view. Developer can add more table if they want by modifiying 'FragmentCount' variable,
 * InitFragments method.
 */
public class ViewPagerFragment extends Fragment {

    private Fragment[] fragmentTabs=null ;
    private String[] fragmentTabNames=null ;
    private View rootView=null ;
    private static int FragmentCount=2 ;

    public static final String Tag="ViewPagerFragment" ;
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        rootView = inflater.inflate(R.layout.fragment_main, container, false);

        InitFragments();

        ViewPager pager = (ViewPager) rootView.findViewById(R.id.pager);
        pager.setAdapter(new MainFragmentPagerAdapter(getChildFragmentManager()));

        //Log.i(toString(),"On Create View called") ;

        return rootView ;
    }

    /**
     * initialize fragments, in which tab specs are added
     * you should put code for adding new tab spec
     */
    private void InitFragments(){

        //initialize fragments
        fragmentTabs=new Fragment[FragmentCount] ;
        fragmentTabs[0]=new SleepManageFragment() ;
        fragmentTabs[1]=new StatisticManageSelectFragment() ;
        //fragmentTabs[2]=new SettingFragment() ;

        //set fragments' name
        fragmentTabNames=new String[FragmentCount] ;
        fragmentTabNames[0]="Sleep" ;
        fragmentTabNames[1]="Statistics" ;
        //fragmentTabNames[2]="Setting" ;
    }

    /**
     * fragment adapter of view pager fragment
     */
    private class MainFragmentPagerAdapter extends FragmentPagerAdapter{


        public MainFragmentPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            return fragmentTabs[position] ;
        }


        @Override
        public int getCount() {
            return FragmentCount ;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return fragmentTabNames[position] ;
        }
    }


}
