/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_androidtown_sleeper_propclasses_dataprocessor_manager_clDataProcessor_clSleepStateClassifier */

#ifndef _Included_org_androidtown_sleeper_propclasses_dataprocessor_manager_clDataProcessor$clSleepStateClassifier
#define _Included_org_androidtown_sleeper_propclasses_dataprocessor_manager_clDataProcessor$clSleepStateClassifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_androidtown_sleeper_propclasses_dataprocessor_manager_clClassifier
 * Method:    doClassificationNative
 * Signature: ([[D[[IILjava/lang/String;[I[D)I
 */
JNIEXPORT jint JNICALL doClassificationNative
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint, jstring, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
